/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/notFound'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWorkflowRouteImport } from './routes/_authenticated/workflow'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTrackingRouteImport } from './routes/_authenticated/tracking'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedSettlementRouteImport } from './routes/_authenticated/settlement'
import { Route as AuthenticatedQuotesRouteImport } from './routes/_authenticated/quotes'
import { Route as AuthenticatedQualityRouteImport } from './routes/_authenticated/quality'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedProcurementRouteImport } from './routes/_authenticated/procurement'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedIntegrationRouteImport } from './routes/_authenticated/integration'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCostRouteImport } from './routes/_authenticated/cost'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated/contracts'
import { Route as AuthenticatedAiAssistantRouteImport } from './routes/_authenticated/ai-assistant'
import { Route as AuthenticatedAfterSalesRouteImport } from './routes/_authenticated/after-sales'
import { Route as AuthenticatedShipRepairIndexRouteImport } from './routes/_authenticated/ship-repair/index'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedShipRepairTasksRouteImport } from './routes/_authenticated/ship-repair/tasks'
import { Route as AuthenticatedShipRepairRiskDashboardRouteImport } from './routes/_authenticated/ship-repair/risk-dashboard'
import { Route as AuthenticatedShipRepairRepairPlansRouteImport } from './routes/_authenticated/ship-repair/repair-plans'
import { Route as AuthenticatedShipRepairProjectsRouteImport } from './routes/_authenticated/ship-repair/projects'
import { Route as AuthenticatedShipRepairNcrsRouteImport } from './routes/_authenticated/ship-repair/ncrs'
import { Route as AuthenticatedShipRepairIsoArchiveRouteImport } from './routes/_authenticated/ship-repair/iso-archive'
import { Route as AuthenticatedShipRepairDashboardRouteImport } from './routes/_authenticated/ship-repair/dashboard'
import { Route as AuthenticatedShipRepairDailyReportsRouteImport } from './routes/_authenticated/ship-repair/daily-reports'
import { Route as AuthenticatedShipRepairDailyLogsRouteImport } from './routes/_authenticated/ship-repair/daily-logs'
import { Route as AuthenticatedQuotesExcelRouteImport } from './routes/_authenticated/quotes/excel'
import { Route as AuthenticatedProcurementIdRouteImport } from './routes/_authenticated/procurement/$id'
import { Route as AuthenticatedOrdersKanbanRouteImport } from './routes/_authenticated/orders/kanban'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders/$id'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/notFound',
  path: '/notFound',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkflowRoute = AuthenticatedWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrackingRoute = AuthenticatedTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettlementRoute = AuthenticatedSettlementRouteImport.update({
  id: '/settlement',
  path: '/settlement',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuotesRoute = AuthenticatedQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQualityRoute = AuthenticatedQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProcurementRoute =
  AuthenticatedProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationRoute =
  AuthenticatedIntegrationRouteImport.update({
    id: '/integration',
    path: '/integration',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCostRoute = AuthenticatedCostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiAssistantRoute =
  AuthenticatedAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAfterSalesRoute = AuthenticatedAfterSalesRouteImport.update({
  id: '/after-sales',
  path: '/after-sales',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShipRepairIndexRoute =
  AuthenticatedShipRepairIndexRouteImport.update({
    id: '/ship-repair/',
    path: '/ship-repair/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShipRepairTasksRoute =
  AuthenticatedShipRepairTasksRouteImport.update({
    id: '/ship-repair/tasks',
    path: '/ship-repair/tasks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShipRepairRiskDashboardRoute =
  AuthenticatedShipRepairRiskDashboardRouteImport.update({
    id: '/ship-repair/risk-dashboard',
    path: '/ship-repair/risk-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShipRepairRepairPlansRoute =
  AuthenticatedShipRepairRepairPlansRouteImport.update({
    id: '/ship-repair/repair-plans',
    path: '/ship-repair/repair-plans',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShipRepairProjectsRoute =
  AuthenticatedShipRepairProjectsRouteImport.update({
    id: '/ship-repair/projects',
    path: '/ship-repair/projects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShipRepairNcrsRoute =
  AuthenticatedShipRepairNcrsRouteImport.update({
    id: '/ship-repair/ncrs',
    path: '/ship-repair/ncrs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShipRepairIsoArchiveRoute =
  AuthenticatedShipRepairIsoArchiveRouteImport.update({
    id: '/ship-repair/iso-archive',
    path: '/ship-repair/iso-archive',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShipRepairDashboardRoute =
  AuthenticatedShipRepairDashboardRouteImport.update({
    id: '/ship-repair/dashboard',
    path: '/ship-repair/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShipRepairDailyReportsRoute =
  AuthenticatedShipRepairDailyReportsRouteImport.update({
    id: '/ship-repair/daily-reports',
    path: '/ship-repair/daily-reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShipRepairDailyLogsRoute =
  AuthenticatedShipRepairDailyLogsRouteImport.update({
    id: '/ship-repair/daily-logs',
    path: '/ship-repair/daily-logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuotesExcelRoute =
  AuthenticatedQuotesExcelRouteImport.update({
    id: '/excel',
    path: '/excel',
    getParentRoute: () => AuthenticatedQuotesRoute,
  } as any)
const AuthenticatedProcurementIdRoute =
  AuthenticatedProcurementIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedProcurementRoute,
  } as any)
const AuthenticatedOrdersKanbanRoute =
  AuthenticatedOrdersKanbanRouteImport.update({
    id: '/orders/kanban',
    path: '/orders/kanban',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/notFound': typeof NotFoundRoute
  '/after-sales': typeof AuthenticatedAfterSalesRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/cost': typeof AuthenticatedCostRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integration': typeof AuthenticatedIntegrationRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/procurement': typeof AuthenticatedProcurementRouteWithChildren
  '/products': typeof AuthenticatedProductsRoute
  '/quality': typeof AuthenticatedQualityRoute
  '/quotes': typeof AuthenticatedQuotesRouteWithChildren
  '/settlement': typeof AuthenticatedSettlementRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/tracking': typeof AuthenticatedTrackingRoute
  '/users': typeof AuthenticatedUsersRoute
  '/workflow': typeof AuthenticatedWorkflowRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/orders/kanban': typeof AuthenticatedOrdersKanbanRoute
  '/procurement/$id': typeof AuthenticatedProcurementIdRoute
  '/quotes/excel': typeof AuthenticatedQuotesExcelRoute
  '/ship-repair/daily-logs': typeof AuthenticatedShipRepairDailyLogsRoute
  '/ship-repair/daily-reports': typeof AuthenticatedShipRepairDailyReportsRoute
  '/ship-repair/dashboard': typeof AuthenticatedShipRepairDashboardRoute
  '/ship-repair/iso-archive': typeof AuthenticatedShipRepairIsoArchiveRoute
  '/ship-repair/ncrs': typeof AuthenticatedShipRepairNcrsRoute
  '/ship-repair/projects': typeof AuthenticatedShipRepairProjectsRoute
  '/ship-repair/repair-plans': typeof AuthenticatedShipRepairRepairPlansRoute
  '/ship-repair/risk-dashboard': typeof AuthenticatedShipRepairRiskDashboardRoute
  '/ship-repair/tasks': typeof AuthenticatedShipRepairTasksRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/ship-repair/': typeof AuthenticatedShipRepairIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/notFound': typeof NotFoundRoute
  '/after-sales': typeof AuthenticatedAfterSalesRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/cost': typeof AuthenticatedCostRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integration': typeof AuthenticatedIntegrationRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/procurement': typeof AuthenticatedProcurementRouteWithChildren
  '/products': typeof AuthenticatedProductsRoute
  '/quality': typeof AuthenticatedQualityRoute
  '/quotes': typeof AuthenticatedQuotesRouteWithChildren
  '/settlement': typeof AuthenticatedSettlementRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/tracking': typeof AuthenticatedTrackingRoute
  '/users': typeof AuthenticatedUsersRoute
  '/workflow': typeof AuthenticatedWorkflowRoute
  '/': typeof AuthenticatedIndexRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/orders/kanban': typeof AuthenticatedOrdersKanbanRoute
  '/procurement/$id': typeof AuthenticatedProcurementIdRoute
  '/quotes/excel': typeof AuthenticatedQuotesExcelRoute
  '/ship-repair/daily-logs': typeof AuthenticatedShipRepairDailyLogsRoute
  '/ship-repair/daily-reports': typeof AuthenticatedShipRepairDailyReportsRoute
  '/ship-repair/dashboard': typeof AuthenticatedShipRepairDashboardRoute
  '/ship-repair/iso-archive': typeof AuthenticatedShipRepairIsoArchiveRoute
  '/ship-repair/ncrs': typeof AuthenticatedShipRepairNcrsRoute
  '/ship-repair/projects': typeof AuthenticatedShipRepairProjectsRoute
  '/ship-repair/repair-plans': typeof AuthenticatedShipRepairRepairPlansRoute
  '/ship-repair/risk-dashboard': typeof AuthenticatedShipRepairRiskDashboardRoute
  '/ship-repair/tasks': typeof AuthenticatedShipRepairTasksRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/ship-repair': typeof AuthenticatedShipRepairIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/notFound': typeof NotFoundRoute
  '/_authenticated/after-sales': typeof AuthenticatedAfterSalesRoute
  '/_authenticated/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/_authenticated/contracts': typeof AuthenticatedContractsRoute
  '/_authenticated/cost': typeof AuthenticatedCostRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/integration': typeof AuthenticatedIntegrationRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/procurement': typeof AuthenticatedProcurementRouteWithChildren
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/quality': typeof AuthenticatedQualityRoute
  '/_authenticated/quotes': typeof AuthenticatedQuotesRouteWithChildren
  '/_authenticated/settlement': typeof AuthenticatedSettlementRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/tracking': typeof AuthenticatedTrackingRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/workflow': typeof AuthenticatedWorkflowRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/_authenticated/orders/kanban': typeof AuthenticatedOrdersKanbanRoute
  '/_authenticated/procurement/$id': typeof AuthenticatedProcurementIdRoute
  '/_authenticated/quotes/excel': typeof AuthenticatedQuotesExcelRoute
  '/_authenticated/ship-repair/daily-logs': typeof AuthenticatedShipRepairDailyLogsRoute
  '/_authenticated/ship-repair/daily-reports': typeof AuthenticatedShipRepairDailyReportsRoute
  '/_authenticated/ship-repair/dashboard': typeof AuthenticatedShipRepairDashboardRoute
  '/_authenticated/ship-repair/iso-archive': typeof AuthenticatedShipRepairIsoArchiveRoute
  '/_authenticated/ship-repair/ncrs': typeof AuthenticatedShipRepairNcrsRoute
  '/_authenticated/ship-repair/projects': typeof AuthenticatedShipRepairProjectsRoute
  '/_authenticated/ship-repair/repair-plans': typeof AuthenticatedShipRepairRepairPlansRoute
  '/_authenticated/ship-repair/risk-dashboard': typeof AuthenticatedShipRepairRiskDashboardRoute
  '/_authenticated/ship-repair/tasks': typeof AuthenticatedShipRepairTasksRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/ship-repair/': typeof AuthenticatedShipRepairIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/notFound'
    | '/after-sales'
    | '/ai-assistant'
    | '/contracts'
    | '/cost'
    | '/customers'
    | '/dashboard'
    | '/integration'
    | '/inventory'
    | '/knowledge'
    | '/messages'
    | '/procurement'
    | '/products'
    | '/quality'
    | '/quotes'
    | '/settlement'
    | '/suppliers'
    | '/tracking'
    | '/users'
    | '/workflow'
    | '/orders/$id'
    | '/orders/kanban'
    | '/procurement/$id'
    | '/quotes/excel'
    | '/ship-repair/daily-logs'
    | '/ship-repair/daily-reports'
    | '/ship-repair/dashboard'
    | '/ship-repair/iso-archive'
    | '/ship-repair/ncrs'
    | '/ship-repair/projects'
    | '/ship-repair/repair-plans'
    | '/ship-repair/risk-dashboard'
    | '/ship-repair/tasks'
    | '/orders/'
    | '/ship-repair/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/notFound'
    | '/after-sales'
    | '/ai-assistant'
    | '/contracts'
    | '/cost'
    | '/customers'
    | '/dashboard'
    | '/integration'
    | '/inventory'
    | '/knowledge'
    | '/messages'
    | '/procurement'
    | '/products'
    | '/quality'
    | '/quotes'
    | '/settlement'
    | '/suppliers'
    | '/tracking'
    | '/users'
    | '/workflow'
    | '/'
    | '/orders/$id'
    | '/orders/kanban'
    | '/procurement/$id'
    | '/quotes/excel'
    | '/ship-repair/daily-logs'
    | '/ship-repair/daily-reports'
    | '/ship-repair/dashboard'
    | '/ship-repair/iso-archive'
    | '/ship-repair/ncrs'
    | '/ship-repair/projects'
    | '/ship-repair/repair-plans'
    | '/ship-repair/risk-dashboard'
    | '/ship-repair/tasks'
    | '/orders'
    | '/ship-repair'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/notFound'
    | '/_authenticated/after-sales'
    | '/_authenticated/ai-assistant'
    | '/_authenticated/contracts'
    | '/_authenticated/cost'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/integration'
    | '/_authenticated/inventory'
    | '/_authenticated/knowledge'
    | '/_authenticated/messages'
    | '/_authenticated/procurement'
    | '/_authenticated/products'
    | '/_authenticated/quality'
    | '/_authenticated/quotes'
    | '/_authenticated/settlement'
    | '/_authenticated/suppliers'
    | '/_authenticated/tracking'
    | '/_authenticated/users'
    | '/_authenticated/workflow'
    | '/_authenticated/'
    | '/_authenticated/orders/$id'
    | '/_authenticated/orders/kanban'
    | '/_authenticated/procurement/$id'
    | '/_authenticated/quotes/excel'
    | '/_authenticated/ship-repair/daily-logs'
    | '/_authenticated/ship-repair/daily-reports'
    | '/_authenticated/ship-repair/dashboard'
    | '/_authenticated/ship-repair/iso-archive'
    | '/_authenticated/ship-repair/ncrs'
    | '/_authenticated/ship-repair/projects'
    | '/_authenticated/ship-repair/repair-plans'
    | '/_authenticated/ship-repair/risk-dashboard'
    | '/_authenticated/ship-repair/tasks'
    | '/_authenticated/orders/'
    | '/_authenticated/ship-repair/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notFound': {
      id: '/notFound'
      path: '/notFound'
      fullPath: '/notFound'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflow': {
      id: '/_authenticated/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof AuthenticatedWorkflowRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tracking': {
      id: '/_authenticated/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof AuthenticatedTrackingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settlement': {
      id: '/_authenticated/settlement'
      path: '/settlement'
      fullPath: '/settlement'
      preLoaderRoute: typeof AuthenticatedSettlementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quotes': {
      id: '/_authenticated/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof AuthenticatedQuotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quality': {
      id: '/_authenticated/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AuthenticatedQualityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/procurement': {
      id: '/_authenticated/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof AuthenticatedProcurementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integration': {
      id: '/_authenticated/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof AuthenticatedIntegrationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cost': {
      id: '/_authenticated/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof AuthenticatedCostRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-assistant': {
      id: '/_authenticated/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AuthenticatedAiAssistantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/after-sales': {
      id: '/_authenticated/after-sales'
      path: '/after-sales'
      fullPath: '/after-sales'
      preLoaderRoute: typeof AuthenticatedAfterSalesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ship-repair/': {
      id: '/_authenticated/ship-repair/'
      path: '/ship-repair'
      fullPath: '/ship-repair/'
      preLoaderRoute: typeof AuthenticatedShipRepairIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ship-repair/tasks': {
      id: '/_authenticated/ship-repair/tasks'
      path: '/ship-repair/tasks'
      fullPath: '/ship-repair/tasks'
      preLoaderRoute: typeof AuthenticatedShipRepairTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ship-repair/risk-dashboard': {
      id: '/_authenticated/ship-repair/risk-dashboard'
      path: '/ship-repair/risk-dashboard'
      fullPath: '/ship-repair/risk-dashboard'
      preLoaderRoute: typeof AuthenticatedShipRepairRiskDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ship-repair/repair-plans': {
      id: '/_authenticated/ship-repair/repair-plans'
      path: '/ship-repair/repair-plans'
      fullPath: '/ship-repair/repair-plans'
      preLoaderRoute: typeof AuthenticatedShipRepairRepairPlansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ship-repair/projects': {
      id: '/_authenticated/ship-repair/projects'
      path: '/ship-repair/projects'
      fullPath: '/ship-repair/projects'
      preLoaderRoute: typeof AuthenticatedShipRepairProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ship-repair/ncrs': {
      id: '/_authenticated/ship-repair/ncrs'
      path: '/ship-repair/ncrs'
      fullPath: '/ship-repair/ncrs'
      preLoaderRoute: typeof AuthenticatedShipRepairNcrsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ship-repair/iso-archive': {
      id: '/_authenticated/ship-repair/iso-archive'
      path: '/ship-repair/iso-archive'
      fullPath: '/ship-repair/iso-archive'
      preLoaderRoute: typeof AuthenticatedShipRepairIsoArchiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ship-repair/dashboard': {
      id: '/_authenticated/ship-repair/dashboard'
      path: '/ship-repair/dashboard'
      fullPath: '/ship-repair/dashboard'
      preLoaderRoute: typeof AuthenticatedShipRepairDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ship-repair/daily-reports': {
      id: '/_authenticated/ship-repair/daily-reports'
      path: '/ship-repair/daily-reports'
      fullPath: '/ship-repair/daily-reports'
      preLoaderRoute: typeof AuthenticatedShipRepairDailyReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ship-repair/daily-logs': {
      id: '/_authenticated/ship-repair/daily-logs'
      path: '/ship-repair/daily-logs'
      fullPath: '/ship-repair/daily-logs'
      preLoaderRoute: typeof AuthenticatedShipRepairDailyLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quotes/excel': {
      id: '/_authenticated/quotes/excel'
      path: '/excel'
      fullPath: '/quotes/excel'
      preLoaderRoute: typeof AuthenticatedQuotesExcelRouteImport
      parentRoute: typeof AuthenticatedQuotesRoute
    }
    '/_authenticated/procurement/$id': {
      id: '/_authenticated/procurement/$id'
      path: '/$id'
      fullPath: '/procurement/$id'
      preLoaderRoute: typeof AuthenticatedProcurementIdRouteImport
      parentRoute: typeof AuthenticatedProcurementRoute
    }
    '/_authenticated/orders/kanban': {
      id: '/_authenticated/orders/kanban'
      path: '/orders/kanban'
      fullPath: '/orders/kanban'
      preLoaderRoute: typeof AuthenticatedOrdersKanbanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedProcurementRouteChildren {
  AuthenticatedProcurementIdRoute: typeof AuthenticatedProcurementIdRoute
}

const AuthenticatedProcurementRouteChildren: AuthenticatedProcurementRouteChildren =
  {
    AuthenticatedProcurementIdRoute: AuthenticatedProcurementIdRoute,
  }

const AuthenticatedProcurementRouteWithChildren =
  AuthenticatedProcurementRoute._addFileChildren(
    AuthenticatedProcurementRouteChildren,
  )

interface AuthenticatedQuotesRouteChildren {
  AuthenticatedQuotesExcelRoute: typeof AuthenticatedQuotesExcelRoute
}

const AuthenticatedQuotesRouteChildren: AuthenticatedQuotesRouteChildren = {
  AuthenticatedQuotesExcelRoute: AuthenticatedQuotesExcelRoute,
}

const AuthenticatedQuotesRouteWithChildren =
  AuthenticatedQuotesRoute._addFileChildren(AuthenticatedQuotesRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAfterSalesRoute: typeof AuthenticatedAfterSalesRoute
  AuthenticatedAiAssistantRoute: typeof AuthenticatedAiAssistantRoute
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRoute
  AuthenticatedCostRoute: typeof AuthenticatedCostRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIntegrationRoute: typeof AuthenticatedIntegrationRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedProcurementRoute: typeof AuthenticatedProcurementRouteWithChildren
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedQualityRoute: typeof AuthenticatedQualityRoute
  AuthenticatedQuotesRoute: typeof AuthenticatedQuotesRouteWithChildren
  AuthenticatedSettlementRoute: typeof AuthenticatedSettlementRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedTrackingRoute: typeof AuthenticatedTrackingRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWorkflowRoute: typeof AuthenticatedWorkflowRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
  AuthenticatedOrdersKanbanRoute: typeof AuthenticatedOrdersKanbanRoute
  AuthenticatedShipRepairDailyLogsRoute: typeof AuthenticatedShipRepairDailyLogsRoute
  AuthenticatedShipRepairDailyReportsRoute: typeof AuthenticatedShipRepairDailyReportsRoute
  AuthenticatedShipRepairDashboardRoute: typeof AuthenticatedShipRepairDashboardRoute
  AuthenticatedShipRepairIsoArchiveRoute: typeof AuthenticatedShipRepairIsoArchiveRoute
  AuthenticatedShipRepairNcrsRoute: typeof AuthenticatedShipRepairNcrsRoute
  AuthenticatedShipRepairProjectsRoute: typeof AuthenticatedShipRepairProjectsRoute
  AuthenticatedShipRepairRepairPlansRoute: typeof AuthenticatedShipRepairRepairPlansRoute
  AuthenticatedShipRepairRiskDashboardRoute: typeof AuthenticatedShipRepairRiskDashboardRoute
  AuthenticatedShipRepairTasksRoute: typeof AuthenticatedShipRepairTasksRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedShipRepairIndexRoute: typeof AuthenticatedShipRepairIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAfterSalesRoute: AuthenticatedAfterSalesRoute,
  AuthenticatedAiAssistantRoute: AuthenticatedAiAssistantRoute,
  AuthenticatedContractsRoute: AuthenticatedContractsRoute,
  AuthenticatedCostRoute: AuthenticatedCostRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIntegrationRoute: AuthenticatedIntegrationRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedProcurementRoute: AuthenticatedProcurementRouteWithChildren,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedQualityRoute: AuthenticatedQualityRoute,
  AuthenticatedQuotesRoute: AuthenticatedQuotesRouteWithChildren,
  AuthenticatedSettlementRoute: AuthenticatedSettlementRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedTrackingRoute: AuthenticatedTrackingRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWorkflowRoute: AuthenticatedWorkflowRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
  AuthenticatedOrdersKanbanRoute: AuthenticatedOrdersKanbanRoute,
  AuthenticatedShipRepairDailyLogsRoute: AuthenticatedShipRepairDailyLogsRoute,
  AuthenticatedShipRepairDailyReportsRoute:
    AuthenticatedShipRepairDailyReportsRoute,
  AuthenticatedShipRepairDashboardRoute: AuthenticatedShipRepairDashboardRoute,
  AuthenticatedShipRepairIsoArchiveRoute:
    AuthenticatedShipRepairIsoArchiveRoute,
  AuthenticatedShipRepairNcrsRoute: AuthenticatedShipRepairNcrsRoute,
  AuthenticatedShipRepairProjectsRoute: AuthenticatedShipRepairProjectsRoute,
  AuthenticatedShipRepairRepairPlansRoute:
    AuthenticatedShipRepairRepairPlansRoute,
  AuthenticatedShipRepairRiskDashboardRoute:
    AuthenticatedShipRepairRiskDashboardRoute,
  AuthenticatedShipRepairTasksRoute: AuthenticatedShipRepairTasksRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedShipRepairIndexRoute: AuthenticatedShipRepairIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
